[package]
name = "stm32f103-tutorial"
version = "0.1.0"
edition = "2021"
authors = ["silent-rain"]
license = "LICENSE"
repository = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "app/helloworld",
    "app/timer_blinky",
    "app/delay_blinky",
    "app/turns_user_led",
    "app/blinky",
    "app/blinky_led_array",
    "app/tim2_timer_delay_blinky",
    "app/led_flow_light",
    "app/buzzer",
    "app/key_control_led",
]

[dependencies]
embedded-hal = "1.0.0-alpha.11"
nb = "1"
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
# Panic behaviour, see https://crates.io/keywords/panic-impl for alternatives
panic-halt = "0.2.0"
# 开发板型号: STM32F103C8T6
stm32f1xx-hal = {version = "0.10.0", features = ["rt", "stm32f103", "high"]}

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
